-- Superseded by 20260717171104_5883c0bf-7223-44bd-bb03-22177cccf4dd.sql, which creates
-- public.admin_settings with the schema (provider, mode, publishable_key, currency,
-- platform_fee_percent, payment_enabled, ...) that the app actually reads/writes.
-- This file previously created a conflicting admin_settings table with different columns
-- (provider_fee_percent, stripe_account_id) and used invalid syntax
-- ("FOR INSERT, UPDATE, DELETE" is not valid in CREATE POLICY), so it could never apply
-- cleanly. Left as a no-op to preserve migration history without breaking fresh deploys.
